# -*- coding: utf-8 -*-
"""
Created on Wed Jan 22 13:14:04 2020

@author: Ryan.Worth
"""
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
##1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

## add even fibonacci numbers to a list
nums = []
a = 0  ##first position
b = 1  ##second position
limit = 4000000
while True:
   c = a + b
   if c >= limit:
      break
   if c % 2 == 0:       
       nums.append(c) ## add to list if even
   a = b ## move positions along
   b = c   
print(nums) ## list of all even fibonacci numbers < 4000000
print(sum(nums)) ##sum them up
## answer = 4613732